repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        exclude: "models/notebooks/.*"
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"


  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", --line-length=99]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        # args: ["--exclude", "<FOO>", "--line-length", "99"]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: |
          (?x) (
          )
    #   - id: flake8
    #     files: ^<FOO_DIR>
    #     args: [--append-config, <FOO_DIR>/.flake8]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
      - id: nbqa-isort

  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.7  # CURRENT_TAG/COMMIT_HASH
    hooks:
      - id: jupytext
        args: [--sync]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
